name: generic-ci

on:
  push:
    branches: [ main ]
    paths:
    - 'check.ps1'
    - 'rg/**'
    - '.github/workflows/generic.yml'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  perform-cicd:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run deploy script
        shell: pwsh
        run: |
          ./deploy-any.ps1
