name: simple-storage-ci

on:
  push:
    branches: [ main ]
    paths:
    - 'rg/simple-storage/**'
    - '.github/workflows/simple-storage.yml'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: fetch code
        uses: actions/checkout@v2

      - name: login to azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: create artifact
        uses: actions/upload-artifact@2
        with:
          name: bicep
          path: 'rg/simple-storage/**''

      - name: run deploy script
        shell: pwsh
        run: |
          Set-Location -Path ./rg/simple-storage
          ./deploy.ps1
