name: todo-ci

on:
  push:
    branches: [ main ]
    paths:
    - 'rg/todo/**'
    - '.github/workflows/todo.yml'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  perform-cicd:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run deploy script
        shell: pwsh
        run: |
          Set-Location -Path ./rg/todo
          ./deploy.ps1
